### ISSUE TITLE
todo list V2

### ISSUE THREAD

**Issue by benjy8001** [benjy8001/web-cv#2]
- [x]  Makefile stop (down --volumes)
- [x] Fix db connection issue with SF 5.3
- [ ] Look at .htaccess (LWS conf) (=> remove /index.php, ...)
- [x] Send mail with swiftmail
- [x] Form build for contact form
- [ ] Macro twig for each parts (comp, skills, ...)
- [x] Auto composer install
- [x] Auto migration
- [x] Cookie consent (https://github.com/ConnectHolland/cookie-consent-bundle)
- [x] Custom 500/404 pages
- [x] Timestamtable entity

**Comment by benjy8001** [comment]
https://gist.github.com/alch/7766993

**Comment by benjy8001** [comment]
Add doctrine event query loguer (in file or database)

**Comment by benjy8001** [comment]
- [ ] docker build, and use image for running
- [x] Maybe add host-manager
- [ ] Ngninx proxy with SSL cert
- [ ] dockerignore file
- [ ] TU
- [x] CI github
